<<<<<<< HEAD
# Generated by Django 2.0 on 2018-07-30 14:26
=======
# Generated by Django 2.0 on 2018-07-24 03:49
>>>>>>> f4b2e79bb7a14df2b477b03708f4a844dabc0ded

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('nickname', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('farmer', '农场主'), ('consumer', '消费者')], default='consumer', max_length=100)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account_user',
                'abstract': False,
            },
        ),
    ]
