# Generated by Django 2.0 on 2018-07-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='account_user',
        ),
    ]
